//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

namespace ListPlanner_Granny.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListItem
    {
        public int ListItemID { get; set; }
        public bool IsDone { get; set; }
        public string ItemName { get; set; }
        public int ToDoListID { get; set; }
    
        public virtual ToDoList ToDoList { get; set; }
    }
}
